### ISSUE TITLE
Updated key server for ROS kinetic

### ISSUE THREAD

**Issue by MixieVR** [felixduvallet/ros-travis-integration#19]
Hi there!

First of all thanks for this repo, it has helped me a lot with my ROS projects.

This weekend the travis builds started failing for the kinetic distro with the following error:
```
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
The command "sudo apt-get install -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-ros-base" failed and exited with 100 during .
```

This was caused by the key server that apparently no longer works on line 72 of travis.yml:
```
- sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
```

I replaced this with 
```
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
``` 
which is the key server used in the ros tutorials.

Now the travis build works again. Not sure if this is the correct way of resolving this problem but I thought I'd share anyway.

**Comment by gsilano** [comment]
Hi @maximliefaard!! Currently, as you can see from my script (it is available at the [link](https://github.com/gsilano/BebopS/blob/dev/sphinx/.travis.yml)), I'm used to installing ROS Kinetic in this way:

```
env:
  global:
    - ROS_DISTRO=kinetic
    - ROS_CI_DESKTOP="`lsb_release -cs`"  # e.g. [precise|trusty|...]

before_install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo rm /var/lib/dpkg/lock
  - sudo dpkg --configure -a
  - sudo apt-get update
  - sudo apt-get install ros-$ROS_DISTRO-desktop-full
```

**Comment by MixieVR** [comment]
Ah nice @gsilano! 
Does this ensure that you do not need to update the apt-key command later?

**Comment by gsilano** [comment]
Mhmm, actually I don’t know. Try using my script and let me know if you can fix the issue or not.

**Comment by MixieVR** [comment]
Yea this also fixes it!
But my suggestion works too: `sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654`

The apt-key command in this repo is still outdated but fortunately I can now continue with my own travis builds.

**Comment by gsilano** [comment]
Therefore, I think you can close the issue :smile:

**Comment by felixduvallet** [comment]
Hi @maximliefaard . Thanks for the report and fix suggestion. I believe it will fix the travis build file, although another issue is preventing the example packages from successfully building. I'll keep looking at this and complete the pull request #20 .
There's no need to change more than the one line you posted in the .travis file from what I can tell so far.

**Comment by felixduvallet** [comment]
Okay, PR #20 fixes this (at the cost of dropping support for jade). Thanks for reporting this @maximliefaard. Please let me know if this fixes the issue for you, in the meantime I will close this.
