### ISSUE TITLE
Can't find ros/ros.h when building audio_user.cpp

### ISSUE THREAD

**Issue by kleinma** [felixduvallet/ros-travis-integration#5]
I gave your code a quick try on Travis-CI. `README.md` is the only file I changed before I pushed the code. Almost everything worked as expected! However, I got the following error when building `audio_user.cpp`:

```
[ 71%] Building CXX object ros-travis-integration/ros_pkg_with_dependencies/CMakeFiles/audio_user.dir/src/audio_user.cpp.o
/home/travis/catkin_ws/src/ros-travis-integration/ros_pkg_with_dependencies/src/audio_user.cpp:1:21: fatal error: ros/ros.h: No such file or directory
 #include "ros/ros.h"
                     ^
compilation terminated.
[ 71%] Built target basic_ros_pkg_generate_messages_lisp
Linking CXX shared library /home/travis/catkin_ws/devel/lib/libsquare.so
[ 85%] make[2]: *** [ros-travis-integration/ros_pkg_with_dependencies/CMakeFiles/audio_user.dir/src/audio_user.cpp.o] Error 1
make[1]: *** [ros-travis-integration/ros_pkg_with_dependencies/CMakeFiles/audio_user.dir/all] Error 2
```

You can view the entire process [here](https://travis-ci.org/kleinma/ros-travis-integration). (As of 5-5-16. I'm not sure how to get a permalink to this specific output.)

**Comment by kleinma** [comment]
Combing through our respective Travis-CI outputs, I see some differences:
- [cmake warnings](https://travis-ci.org/felixduvallet/ros-travis-integration#L1495) in your code.
- Starting [here in mine](https://travis-ci.org/kleinma/ros-travis-integration#L1500) and [here in yours](https://travis-ci.org/felixduvallet/ros-travis-integration#L1525), scanning, building, linking, and generating happen in a different order.

**Comment by felixduvallet** [comment]
Thanks for reporting this! I'm pushing a no-op commit to replicate this. My guess is something changed on the ROS side, I'll have a deeper look tomorrow.

**Comment by felixduvallet** [comment]
So I'm not really sure _why_ things broke, but it's possibly due to an upstream change. It looked like the include path was wrong in catkin_make, probably due to a missing ROS environment variable (usually this is because of a missed source of setup.bash).

I was able to resolve this by sourcing the global setup.bash one more time before building.

Let me know if this also resolves the issue on your side.

**Comment by tsaoyu** [comment]
Source the resulting setup file after `catkin_make` would solve problems with other package related error.
https://github.com/Maritime-Robotics-Student-Society/sailing-robot/commit/85ffacf8374678feb2aaefcd2816dc12ee6f803d
