### ISSUE TITLE
Can't find ros-$ROS_DISTRO-catkin

### ISSUE THREAD

**Issue by garethellis0** [felixduvallet/ros-travis-integration#7]
Whenever I try to use this, on `sudo apt-get install -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin"` I get E: Unable`to locate package ros-kinetic-catkin` and the corresponding Travis-CI error The command `"sudo apt-get install -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-catkin"` failed and exited with 100 during .. Any thoughts on what might be going wrong? I tried replacing the commands with those from the [kinetic wiki](http://wiki.ros.org/kinetic/Installation/Ubuntu) but got the same error

**Comment by felixduvallet** [comment]
Thanks for submitting an issue about this. I haven't tested ROS releases besides indigo, so give me a bit to try it out and I'll get back to you.

Do you have a complete build log somewhere?

**Comment by felixduvallet** [comment]
Kinetic is only available for Ubuntu Wily and Xenial ([see doc](http://wiki.ros.org/kinetic/Installation/Ubuntu)).

Unfortunately since Travis only supports Ubuntu up to Trusty, ROS kinetic cannot be integrated into Travis at this time. I added a note in the readme: e97af3d .

**Comment by garethellis0** [comment]
Cheers, I'll see if I can get it running with docker
